name: Bright

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MySQL database
        run: |
          docker-compose up -d

      - name: Copy environment file
        run: |
          cp .env.example .env

      - name: Set JWT_SECRET in .env
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Start application
        env:
          ALLOWED_ORIGINS: http://localhost:3000,https://example.com
          DB_HOST: localhost:53306
          DB_NAME: golang_realworld
          DB_PASSWORD: password
          DB_USER: root
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          go run main.go &

      - name: Probe application readiness
        run: |
          for i in {1..30}; do nc -z 127.0.0.1 8080 && exit 0 || sleep 5; done; exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install SecTesterJS dependencies
        run: |
          npm i --save=false --prefix .brightsec @sectester/core@0.47.0 @sectester/repeater@0.47.0 @sectester/scan@0.47.0 @sectester/runner@0.47.0 @sectester/reporter@0.47.0

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 2tiBS9X13Ps5BkKzBdbWgj
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 2tiBS9X13Ps5BkKzBdbWgj
          BRIGHT_AUTH_ID: qgcpDeHpD8L8656LpBCFjW
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:8080
          SECTESTER_SCAN_POOL_SIZE: ${{ vars.SECTESTER_SCAN_POOL_SIZE }}
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts